name: Deploy
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-18.04
    steps:
        with:
          build_dir: client
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
